title: Dokumentasi
lang: en
description: List of documentations from my mistakes that I can refer to later and others can learn from my mistakes to

# Google Services
ga_tracking: G-YLZDCTK9KF
ga_tracking_anonymize_ip: true


## local method ##
# theme: jekyll-rtd-theme
# debug:
#   compress: false
#   dist: true
#   shortcodes: true

## remote method ##
remote_theme: pmarsceill/just-the-docs
color_scheme: dark

readme_index:
  with_frontmatter: true

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
url: ""

# Aux links for the upper right navigation
aux_links:
  "Blog":
    - "https://irawans.com"
  "Landing page":
    - "https://irawan.io"
# "Other link":
  #  - "/irawan.io/web"

#markdown: kramdown
#kramdown:
#    highlighter: rouge
#    syntax_highlighter_opts:
#        block:
#            line_numbers: true
